class ManyInstanceOfDatabaseError(Exception):
    """Исключение, возникающие при попытке создать второй или более экземпляр базы данных"""
